// Reference list of every app role and its permissions
export const ROLES_GUIDE = [
  {
    role: "Owner",
    value: "owner",
    color: "#facc15",
    emoji: "👑",
    level: "Full Access",
    permissions: [
      "Everything an Admin can do",
      "Owner-only settings (Otter Week visibility, Achievements & feature toggles)",
      "Assign the Owner role to others",
      "Manage photos and app-wide configuration",
    ],
  },
  {
    role: "Admin (Flag Officer)",
    value: "admin",
    color: "#f87171",
    emoji: "⚓",
    level: "Admin Level",
    permissions: [
      "Create, edit & delete any event (all groups, recurring series)",
      "Post, pin & delete announcements",
      "Manage sponsors, badges, trophies & nominations",
      "Manage member roles & Otter usernames in Settings",
      "View Stats, scan tickets, import/export attendees",
      "Set sailing status, cancellations & wind limits",
      "Manage duty roster & volunteering",
    ],
  },
  {
    role: "Admiral",
    value: "admiral",
    color: "#38bdf8",
    emoji: "🎖️",
    level: "Admin Level",
    permissions: [
      "Same permissions as Admin (Flag Officer)",
      "Full event, announcement, sponsor & roster management",
      "Manage member roles in Settings",
      "View Stats & scan tickets",
    ],
  },
  {
    role: "Chairman",
    value: "chairman",
    color: "#c084fc",
    emoji: "🏛️",
    level: "Senior",
    permissions: [
      "Create & edit events for all groups",
      "Post, pin & delete announcements",
      "Manage sponsors & duty roster",
      "Set sailing status & cancellations",
      "View Stats & Otter Week tickets",
      "Cannot manage member roles or delete app data",
    ],
  },
  {
    role: "Group Trainers",
    value: "pond_trainer / river1_trainer / river2_trainer / race_trainer / cadet_trainer / fast_trainer",
    color: "#fbbf24",
    emoji: "🧑‍🏫",
    level: "Trainer",
    permissions: [
      "Create & edit events for their own group",
      "Set daily sailing status & boat cancellations",
      "Manage the duty roster & confirm volunteers",
      "Post announcements & award badges",
      "View trophy nominations",
    ],
  },
  {
    role: "Group Members",
    value: "pond / river1 / river2 / race / cadets / fast",
    color: "#34d399",
    emoji: "🛶",
    level: "Member",
    permissions: [
      "View their group's schedule & everyone events",
      "Post & react on the Feed",
      "RSVP to events & buy tickets",
      "Comment on events & set availability",
      "Nominate people for trophies",
    ],
  },
  {
    role: "Group Parents",
    value: "pond_parent / river1_parent / river2_parent / race_parent / cadet_parent / fast_parent",
    color: "#5eead4",
    emoji: "👪",
    level: "Member",
    permissions: [
      "View their group's schedule & announcements",
      "RSVP to events on behalf of their sailor",
      "View the Feed and notices",
    ],
  },
  {
    role: "Viewer",
    value: "viewer",
    color: "#94a3b8",
    emoji: "👀",
    level: "Read-mostly",
    permissions: [
      "View all groups' schedules & announcements",
      "Post announcements & on the Feed",
      "Cannot edit events, sponsors or rosters",
    ],
  },
  {
    role: "Otter Volunteer",
    value: "otter_volunteer (extra group)",
    color: "#818cf8",
    emoji: "🙋",
    level: "Extra Role",
    permissions: [
      "Added on top of any main role",
      "Unlocks the Volunteering page & sign-ups",
    ],
  },
  {
    role: "No Role",
    value: "user",
    color: "#64748b",
    emoji: "⏳",
    level: "Pending",
    permissions: [
      "Awaiting approval by an admin",
      "Can only access the Home & Profile pages",
    ],
  },
];